name: Fetch Associations

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * 0"

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          cache: yarn

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn --immutable

  fetch-and-pr:
    name: Fetch and Pull Request
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          cache: yarn

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Restore Node Modules
        id: node-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Fetch Associations
        env:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_ASSOCIATIONS_DATABASE_ID: ${{ secrets.NOTION_ASSOCIATIONS_DATABASE_ID }}
        run: node ./scripts/fetch-associations/index.mjs

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
